# Generated by Django 5.0.1 on 2024-02-03 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_usercreationform'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Register_User',
        ),
        migrations.RenameField(
            model_name='usercreationform',
            old_name='dob',
            new_name='d_o_b',
        ),
        migrations.RenameField(
            model_name='usercreationform',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='usercreationform',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='usercreationform',
            name='district',
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.district')),
            ],
        ),
    ]
