# Generated by Django 5.0.1 on 2024-02-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_remove_applicationform_account_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fill_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('phone_number', models.PositiveIntegerField()),
                ('mail_id', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=200)),
                ('district', models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kollam', 'Kollam'), ('Pathanamthitta', 'Pathanamthitta'), ('Alappuzha', 'Alappuzha'), ('Kottayam', 'Kottayam'), ('Idukki', 'Idukki'), ('Ernakulam', 'Ernakulam'), ('Thrissur', 'Thrissur'), ('Palakkad', 'Palakkad'), ('Malappuram', 'Malappuram'), ('Kozhikode', 'Kozhikode'), ('Wayanad', 'Wayanad'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod')], max_length=100)),
                ('branch', models.CharField(choices=[('Attingal', 'Attingal'), ('Neyyaattinkara', 'Neyyaattinkara'), ('Kilimanoor', 'Kilimanoor'), ('Varkala', 'Varkala'), ('Kattakkada', 'Kattakkada'), ('Karunagappally', 'Karunagappally'), ('Kadakkal', 'Kadakkal'), ('Kottiyim', 'Kottiyim'), ('Kundara', 'Kundara'), ('Kollam Town', 'Kollam Town'), ('Pathanamthitta Town', 'Pathanamthitta Town'), ('Ranni', 'Ranni'), ('Thiruvalla', 'Thiruvalla'), ('Adoor', 'Adoor'), ('Omalloor', 'Omalloor'), ('Aroor', 'Aroor'), ('Cherthala', 'Cherthala'), ('Haripad', 'Haripad'), ('Kayamkulam', 'Kayamkulam'), ('Mannar', 'Mannar'), ('Pala', 'Pala'), ('Kanjirapally', 'Kanjirapally')], max_length=100)),
                ('type_of_account', models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current'), ('Fixed Deposit', 'Fixed Deposit'), ('Recurring Deposit', 'Recurring Deposit'), ('Overdraft', 'Overdraft'), ('Credit', 'Credit'), ('Debit', 'Debit'), ('Loan', 'Loan'), ('Mortgage', 'Mortgage'), ('Joint', 'Joint'), ('Personal', 'Personal'), ('Corporate', 'Corporate'), ('Government', 'Government'), ('Business', 'Business'), ('Hybrid', 'Hybrid'), ('NRI', 'NRI'), ('Foreign', 'Foreign'), ('Domestic', 'Domestic'), ('Others', 'Others')], max_length=100)),
                ('materials_provided', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AccountType',
        ),
        migrations.DeleteModel(
            name='ApplicationForm',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='district',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
